version: '3'

services:
    gwh_api_web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        ports:
            - "8000:8000"
        image: docker.pkg.github.com/gwh-tech/gwh_api/gwh_api_web:${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}-prerelease${PRERELEASE_VERSION}
        expose:
            - 8000
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/mediafiles
        command: bash -c "uwsgi --socket :8000 --master --enable-threads --module gwh_api.wsgi --logger file:/tmp/uwsgi.log"
