name: Build GWH API Docker Images

on:
  push:
    branches: ['main']
    
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: GitHub Tag
      uses: mathieudutour/github-tag-action@v6.1      
    - name: Log into github docker registry
      run:  echo "Hello" 
