name: Build GWH API Docker Image

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: GitHub Tag
      uses: mathieudutour/github-tag-action@v6.1      
    - name: Log into github docker registry
      run:  echo "Hello" 
