name: Build GWH API Docker Image

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Semantic versioning
      id: versioning
      uses: PaulHatch/semantic-version@v4.0.2
      with:
        branch: main
        tag_prefix: "v"
        major_pattern: "BREAKING CHANGE:"
        minor_pattern: "feat:"
        format: "v${major}.${minor}.${patch}-prerelease${increment}"
    - name: Log into github docker registry
      run:  echo "Hello" 
