name: CI/CD for versioning using Github Actions

on:
  push:
    branches: ['main']
    
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Semantic versioning
      id: versioning
      uses: paulhatch/semantic-version@v5.2.1
      with:
        tag_prefix: "v"
        version_format: "v${major}.${minor}.${patch}"
    - name: Set Docker image version
      run: echo "TAG=${{ steps.versioning.outputs.version }}" >> $GITHUB_ENV  
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token}}
      with:
        tag_name: ${{ steps.versioning.outputs.version}}
        release_name: ${{ steps.versioning.outputs.version }}
